### ISSUE TITLE
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by jayant-lumino** [isaka-james/dhiwise-copy-extension#2]
Context
front-end/index.html
Stack Trace
front-end/index.html:0 (anonymous function)
![Screenshot 2024-08-06 at 5 15 01 PM](https://github.com/user-attachments/assets/675e86a5-9bbf-417e-b175-c157ad250311)

**Comment by isaka-james** [comment]
I don't have much information about your error. Please try viewing the error through the extension devtools so we can figure out what's causing it.

I've tested the extension today, 6th August 2024, and here are my observations:

1. The extension was imported successfully.
   ![Screenshot from 2024-08-06 17-46-48](https://github.com/user-attachments/assets/6c35dad8-4034-4997-8059-e4f75b0763e8)

2. This is the Figma file I used for testing.
   ![Screenshot from 2024-08-06 17-47-56](https://github.com/user-attachments/assets/7b7e7483-224a-4eac-a05f-cf29e1691691)

3. Building the designs from DhiWise.
   ![Screenshot from 2024-08-06 17-50-40](https://github.com/user-attachments/assets/d92e7b5f-8d39-43b9-89a1-0ed2ac4cc71a)
   ![Screenshot from 2024-08-06 17-51-42](https://github.com/user-attachments/assets/3d963ec0-ba11-4b25-a6e1-9277d84bbdec)

4. These are the codes provided by DhiWise, and I also enabled the extension.
   ![Screenshot from 2024-08-06 17-52-16](https://github.com/user-attachments/assets/06a16c7e-802e-4f3d-a00d-7ccaad60a68d)

5. By clicking the `copy code` from the sidebar, I was still able to copy the code and paste it into VSCode.
   ![Screenshot from 2024-08-06 17-53-29](https://github.com/user-attachments/assets/7776e946-74ba-4e94-98e8-2da96ce09cd0)

**Comment by jayant-lumino** [comment]
> I don't have much information about your error. Please try viewing the error through the extension devtools so we can figure out what's causing it.
> 
> I've tested the extension today, 6th August 2024, and here are my observations:
> 
> 1. The extension was imported successfully.
>    ![Screenshot from 2024-08-06 17-46-48](https://private-user-images.githubusercontent.com/76619967/355498956-6c35dad8-4034-4997-8059-e4f75b0763e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDM1NTksIm5iZiI6MTcyMzAwMzI1OSwicGF0aCI6Ii83NjYxOTk2Ny8zNTU0OTg5NTYtNmMzNWRhZDgtNDAzNC00OTk3LTgwNTktZTRmNzViMDc2M2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA0MDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NDk4Y2MwY2VkODEzMDZkZDAxZGU0NWFjYmRmMzkyYjVkMjNlNjhkM2EwNDExMTgxZDQxOWZmNDk4NWRiMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4aUif-n9yd4Ew0iqbElvErUqr6d1P8Rfxsq_x01InjA)
> 2. This is the Figma file I used for testing.
>    ![Screenshot from 2024-08-06 17-47-56](https://private-user-images.githubusercontent.com/76619967/355499214-7b7e7483-224a-4eac-a05f-cf29e1691691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDM1NTksIm5iZiI6MTcyMzAwMzI1OSwicGF0aCI6Ii83NjYxOTk2Ny8zNTU0OTkyMTQtN2I3ZTc0ODMtMjI0YS00ZWFjLWEwNWYtY2YyOWUxNjkxNjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA0MDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MzExMWEwNzA5MzU5MDM1ZDZiYTUyNTI2YTY3NzU1MTZiMGFlOGI5OGVhZGQzZjA4NmE5NTNjNDBhOTdkYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wA67lGp0EnGWXlqaSysQIxqmt7SUCleEW1rTXV1x0Uw)
> 3. Building the designs from DhiWise.
>    ![Screenshot from 2024-08-06 17-50-40](https://private-user-images.githubusercontent.com/76619967/355499600-d92e7b5f-8d39-43b9-89a1-0ed2ac4cc71a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDM1NTksIm5iZiI6MTcyMzAwMzI1OSwicGF0aCI6Ii83NjYxOTk2Ny8zNTU0OTk2MDAtZDkyZTdiNWYtOGQzOS00M2I5LTg5YTEtMGVkMmFjNGNjNzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA0MDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MDdmM2FhMzIxNzQ4YjZiYzJmNTgzOTE2YTdjOWJiYzUzNjQ0MDNmOTRhYTYzNWQ2YjcyNTdmZTYzM2UzYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.076vaOc4fKnZHrAtkYJnjWX6J3lr2ZZi86XleZfiCkY)
>    ![Screenshot from 2024-08-06 17-51-42](https://private-user-images.githubusercontent.com/76619967/355499813-3d963ec0-ba11-4b25-a6e1-9277d84bbdec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDM1NTksIm5iZiI6MTcyMzAwMzI1OSwicGF0aCI6Ii83NjYxOTk2Ny8zNTU0OTk4MTMtM2Q5NjNlYzAtYmExMS00YjI1LWE2ZTEtOTI3N2Q4NGJiZGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA0MDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZDQ4YjQzNjVlOGQ2NjgyYWQ0MDdkNmRhZjFhMTBmN2U4ZjYxYjQ0NWY4MjYzNjk0N2Q0ZWMwOTVjMjM5YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9WVmcJCV0QvSVujSqxITA80m473HuPCkjgA2Szxek50)
> 4. These are the codes provided by DhiWise, and I also enabled the extension.
>    ![Screenshot from 2024-08-06 17-52-16](https://private-user-images.githubusercontent.com/76619967/355500164-06a16c7e-802e-4f3d-a00d-7ccaad60a68d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDM1NTksIm5iZiI6MTcyMzAwMzI1OSwicGF0aCI6Ii83NjYxOTk2Ny8zNTU1MDAxNjQtMDZhMTZjN2UtODAyZS00ZjNkLWEwMGQtN2NjYWFkNjBhNjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA0MDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZDhlNmNkYTM3MjU3OWRjN2U4MmM0YWFiMzkxY2FhMWNjODIxOGQ4NzM1ODdlYTRiZTIxZTNmMmVmMzEzNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pwiYci55F-3PccWnCeK3itxVsWtrQOBfI6N_rLk8tys)
> 5. By clicking the `copy code` from the sidebar, I was still able to copy the code and paste it into VSCode.
>    ![Screenshot from 2024-08-06 17-53-29](https://private-user-images.githubusercontent.com/76619967/355500505-7776e946-74ba-4e94-98e8-2da96ce09cd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDM1NTksIm5iZiI6MTcyMzAwMzI1OSwicGF0aCI6Ii83NjYxOTk2Ny8zNTU1MDA1MDUtNzc3NmU5NDYtNzRiYS00ZTk0LTk4ZTgtMmRhOTZjZTA5Y2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA0MDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NWI0MTg5ZGU5NmY2ZTViZDkxZWI4YWNhYTNjMDlkOTE1ZmM5MjBkNjhiZDdiZDdhZDMwNzc2ZmE2NmVmNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O9jXpuUyf9PbUj9AkngYofUdHaNQYPjZ3j8t3ptxz_g)

Extension imported successfully in my case too. When I toggle the button only then I'm getting this error

**Comment by jayant-lumino** [comment]
Extension worked but the functionality is not working on larger files

**Comment by isaka-james** [comment]
I haven't maintained this tool for a long time. One of the challenges with this tool is handling longer files. If you encounter this issue, please maximize your browser's zoom out, and then click the copy code button to copy the visible code. If the file is very long, you can copy it in parts. Note that the tool copies only the code displayed on the screen.

Additionally, you need to replace any binary spaces with actual spaces in the copied code. I might work on improving the tool this weekend, but this is the current functionality.

**Comment by jayant-lumino** [comment]
Thanks Great work BTW

**Comment by isaka-james** [comment]
Cool man, if you have something you want to improve just `pull request`
